secretGenerator:
- name: mysql-secret
  literals:
  - MYSQL_ROOT_PASSWORD=1234
  - MYSQL_DATABASE=wordpress
  - MYSQL_USER=admin
  - MYSQL_PASSWORD=1234

resources:
  - wordpress-deployment.yaml
  - mysql-pv.yaml
  - mysql-pvc.yaml
  - ingress.yaml
  - cluster-issuer.yaml
