#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: wp-pv
#spec:
  #capacity:
  #  storage: 20Gi
 # accessModes:
  #  - ReadWriteOnce
 # persistentVolumeReclaimPolicy: Retain
  #awsElasticBlockStore:
  #  volumeID: vol-0fd8bf94ba6798dd4  # ضع الـ Volume ID المناسب
 #   fsType: ext4
#  storageClassName: standard

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/wp
