apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNA==  # password: 1234 (base64 encoded)
  MYSQL_DATABASE: d29yZHByZXNz  # database: wordpress (base64 encoded)
  MYSQL_USER: YWRtaW4=  # user: admin (base64 encoded)
  MYSQL_PASSWORD: MTIzNA==  # password: 1234 (base64 encoded)
